// Single shared design system for every PDF the app generates (order
// invoices, dashboard reports, stock receipts, ...). The Order Invoice was
// the original, most polished document in the app, so its layout/branding/
// typography became the template here — every other PDF is built from these
// same pieces so nothing can visually drift from it again.

// Exported so other document builders (e.g. excelExport.ts) can reuse the
// same brand identity instead of re-typing it.
export const BRAND_NAME = 'Mayben traders';
export const BRAND_SUPPORT_PHONE = '+91 73736 74757';
const BRAND_TAGLINE = 'Premium Distribution & Logistics Network ERP';
const BRAND_GSTIN_LINE = `GSTIN: 27AAAAA1111A1Z1 | Support: ${BRAND_SUPPORT_PHONE}`;

export const PDF_STYLE = `
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif; margin: 22px; color: #1e293b; font-size: 11px; }
  .brand { color: #c2410c; font-weight: 800; font-size: 16px; }
  .muted { color: #64748b; font-size: 8px; }
  hr { margin: 6px 0; border: none; border-top: 1px solid #cbd5e1; }
  .doc-title { margin-top: 6px; }
  .doc-title strong { font-size: 11px; color: #0f172a; }
  .doc-title span { font-size: 8px; }
  table { width: 100%; border-collapse: collapse; margin-top: 8px; font-size: 9px; }
  th { background: #f8fafc; text-align: left; padding: 5px 6px; border-bottom: 2px solid #cbd5e1; font-size: 8px; text-transform: uppercase; color: #475569; }
  td { padding: 5px 6px; border-bottom: 1px solid #e2e8f0; }
  .box { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 8px 10px; margin-top: 8px; font-size: 10px; }
  .section-title { font-size: 9px; font-weight: 800; text-transform: uppercase; letter-spacing: 0.4px; color: #475569; margin-top: 14px; margin-bottom: 3px; }
  .info-table td { border: none; vertical-align: top; width: 50%; padding: 0; }
  .summary-line { display: flex; flex-wrap: wrap; column-gap: 26px; row-gap: 3px; margin: 8px 0 2px 0; padding: 6px 0; border-top: 1px solid #e2e8f0; border-bottom: 1px solid #e2e8f0; font-size: 9px; }
  .summary-line .s-label { color: #64748b; font-weight: 700; margin-right: 4px; }
  .summary-line .s-value { font-weight: 800; color: #0f172a; }
  .summary-line .s-value.accent { color: #c2410c; }
`;

function renderHeader(title: string, subtitle: string): string {
  return `
    <div class="brand">${BRAND_NAME}</div>
    <div class="muted">${BRAND_TAGLINE}</div>
    <div class="muted">${BRAND_GSTIN_LINE}</div>
    <hr/>
    <div class="doc-title"><strong>${title}</strong><br/><span class="muted">${subtitle}</span></div>`;
}

function renderFooter(note: string, generatedAt: string): string {
  return `<p class="muted" style="text-align:center;margin-top:16px">${note}<br/>Generated by ${BRAND_NAME} ERP Hub | ${generatedAt}</p>`;
}

/** Two-column info block styled exactly like the invoice's BILL TO / invoice-meta table. */
export function renderInfoTable(leftHtml: string, rightHtml: string): string {
  return `<table class="info-table"><tr><td>${leftHtml}</td><td>${rightHtml}</td></tr></table>`;
}

export interface SummaryItem {
  label: string;
  value: string;
  accent?: boolean;
}

/** Compact, borderless label:value summary line — replaces the old bordered
 * KPI-card grid. Matches the plain, text-based tone of the Order Invoice
 * rather than looking like a dashboard widget. */
export function renderSummaryLine(items: SummaryItem[]): string {
  return `<div class="summary-line">${items
    .map(i => `<span><span class="s-label">${i.label}:</span><span class="s-value${i.accent ? ' accent' : ''}">${i.value}</span></span>`)
    .join('')}</div>`;
}

/** Wraps body content in the full brand header + footer shell every PDF shares. */
export function renderPdfDocument(opts: { title: string; subtitle: string; bodyHtml: string; footerNote: string }): string {
  const generatedAt = new Date().toLocaleString('en-IN');
  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><style>${PDF_STYLE}</style></head><body>
    ${renderHeader(opts.title, opts.subtitle)}
    ${opts.bodyHtml}
    ${renderFooter(opts.footerNote, generatedAt)}
  </body></html>`;
}

// ---------------------------------------------------------------------------
// Filenames — every PDF is named "<Document_Type>_<PREFIX-ID>.pdf" so files
// are self-describing and never collide in a Downloads folder.
// ---------------------------------------------------------------------------

function sanitizeFileNamePart(value: string): string {
  return value.replace(/[^a-zA-Z0-9-]+/g, '_');
}

/** Deterministic 6-digit code derived from a record's real ID — the same
 * record (e.g. the same purchase) always produces the same filename, so
 * re-downloading it doesn't clutter the Downloads folder with near-duplicates. */
function stableDigits(seed: string, length = 6): string {
  let hash = 0;
  for (let i = 0; i < seed.length; i++) {
    hash = (hash * 31 + seed.charCodeAt(i)) >>> 0;
  }
  return String(hash % 10 ** length).padStart(length, '0');
}

/** Time-based 6-digit code for documents with no single backing record (period
 * reports) — each generation is a fresh snapshot, so each download gets its own ID. */
function timeBasedDigits(length = 6): string {
  return String(Date.now() % 10 ** length).padStart(length, '0');
}

/** Builds a reference code like "RS-482913" from a record's own unique ID. */
export function stableRecordRef(prefix: string, recordId: string): string {
  return `${prefix}-${stableDigits(recordId)}`;
}

/** Builds a reference code like "REV-104822" unique to this generation. */
export function freshReportRef(prefix: string): string {
  return `${prefix}-${timeBasedDigits()}`;
}

/** Composes the final "<Document_Type>_<PREFIX-ID>.pdf" filename. */
export function buildPdfFileName(documentLabel: string, refCode: string): string {
  return `${sanitizeFileNamePart(documentLabel)}_${sanitizeFileNamePart(refCode)}.pdf`;
}

const EXTENSION_BY_MIME_TYPE: Record<string, string> = {
  'application/pdf': 'pdf',
  'application/vnd.ms-excel': 'xls',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': 'xlsx',
  'image/jpeg': 'jpg',
  'image/png': 'png',
  'image/webp': 'webp',
  'image/gif': 'gif',
};

/** Same "<Document_Type>_<PREFIX-ID>.<ext>" convention as buildPdfFileName,
 * but for user-uploaded attachments (e.g. a supplier bill photo/PDF/Excel)
 * whose extension isn't fixed - so a downloaded/shared bill is always named
 * after the invoice or bill ID it belongs to instead of the original
 * "IMG_1234.jpg"-style camera/scanner filename, which is meaningless once
 * it's sitting in a Downloads folder next to a dozen other receipts. */
export function buildAttachmentFileName(documentLabel: string, refCode: string, originalName: string, mimeType?: string): string {
  const originalExt = originalName.includes('.') ? originalName.split('.').pop() : undefined;
  const ext = (originalExt && originalExt.length <= 5 ? originalExt.toLowerCase() : undefined)
    || (mimeType && EXTENSION_BY_MIME_TYPE[mimeType])
    || 'dat';
  return `${sanitizeFileNamePart(documentLabel)}_${sanitizeFileNamePart(refCode)}.${ext}`;
}
